export const IinAllConstants = {
  LOGIN: 'LOGIN',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGOUT: 'LOGOUT',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  SAVE_USER_DATA_RESPONSE: 'SAVE_USER_DATA_RESPONSE',
  REGISTER: 'REGISTER',
  GET_RANDOM: 'GET_RANDOM',
  USER_RESPONSE: 'USER_RESPONSE',
  REGISTER_RESPONSE: 'REGISTER_RESPONSE',
  GET_RANDOM_RESPONSE: 'GET_RANDOM_RESPONSE',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  TOGGLE_REGISTER: 'TOGGLE_REGISTER',
  TOGGLE_USERDATA: 'TOGGLE_USERDATA',
  TOGGLE_EDIT: 'TOGGLE_EDIT',
  RECEIVE_FORMAT: 'RECEIVE_FORMAT'
};
