#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekDeepWithin.Views.Book
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Book\Index.cshtml"
    using PagedList.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Book\Index.cshtml"
    using SeekDeepWithin.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Book/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<PagedList.IPagedList<SeekDeepWithin.Models.BookViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Book\Index.cshtml"
  
   ViewBag.Title = "Read";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>Read</h3>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n   ");

WriteLiteral("\r\n   <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Book\Index.cshtml"
      
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Book\Index.cshtml"
        
         int index = 0;
      
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Views\Book\Index.cshtml"
      
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Book\Index.cshtml"
       foreach (var book in Model) {
         if (index == 0) {
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Book\Index.cshtml"
       Write(Html.Raw("<div class=\"row\" data-equalizer>"));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Book\Index.cshtml"
                                                           
         }

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"large-4 small-12 medium-6 columns\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"pricing-table\"");

WriteLiteral(" data-equalizer-watch>\r\n               <li");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                  ");

            
            #line 31 "..\..\Views\Book\Index.cshtml"
             Write(book.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                  <span");

WriteLiteral(" style=\"font-size: small\"");

WriteLiteral(">\r\n                     <a");

WriteAttribute("href", Tuple.Create(" href=\"", 920), Tuple.Create("\"", 995)
            
            #line 33 "..\..\Views\Book\Index.cshtml"
, Tuple.Create(Tuple.Create("", 927), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", "Book", new {id=book.Id}, Request.Url.Scheme)
            
            #line default
            #line hidden
, 927), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"icon-info-sign\"");

WriteLiteral("></i>\r\n                     </a>\r\n                  </span>\r\n");

            
            #line 37 "..\..\Views\Book\Index.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Book\Index.cshtml"
                   if (!string.IsNullOrWhiteSpace (book.SubTitle)) {

            
            #line default
            #line hidden
WriteLiteral("                     <br/>");

WriteLiteral("<small>");

            
            #line 38 "..\..\Views\Book\Index.cshtml"
                            Write(book.SubTitle);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n");

            
            #line 39 "..\..\Views\Book\Index.cshtml"
                  }

            
            #line default
            #line hidden
WriteLiteral("               </li>\r\n               <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n");

WriteLiteral("                  ");

            
            #line 42 "..\..\Views\Book\Index.cshtml"
             Write(Html.Raw(HtmlSanitizer.Sanitize (book.Summary)));

            
            #line default
            #line hidden
WriteLiteral("\r\n               </li>\r\n");

            
            #line 44 "..\..\Views\Book\Index.cshtml"
               
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Book\Index.cshtml"
                if (book.Versions.Count == 0) {

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(">\r\n                     <span");

WriteLiteral(" class=\"label secondary\"");

WriteLiteral(">No information has been entered for this book!</span>\r\n                  </li>\r\n" +
"");

            
            #line 48 "..\..\Views\Book\Index.cshtml"
               } else if (book.Versions.Count == 1 && book.Title == book.Versions[0].Title) {
                  var version = book.Versions [0];

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(" style=\"border-bottom: 0;\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Book\Index.cshtml"
                     
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Book\Index.cshtml"
                      if (version.DefaultReadChapter == 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(">\r\n                           <span");

WriteLiteral(" class=\"label secondary\"");

WriteLiteral(">No information has been entered for this book!</span>\r\n                        <" +
"/li>\r\n");

            
            #line 55 "..\..\Views\Book\Index.cshtml"
                     } else {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2163), Tuple.Create("\"", 2260)
            
            #line 56 "..\..\Views\Book\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2170), Tuple.Create<System.Object, System.Int32>(Url.Action("Read", "Chapter", new{ id = version.DefaultReadChapter }, Request.Url.Scheme)
            
            #line default
            #line hidden
, 2170), false)
);

WriteLiteral(">\r\n                           Read\r\n                        </a>\r\n");

            
            #line 59 "..\..\Views\Book\Index.cshtml"
                     }

            
            #line default
            #line hidden
WriteLiteral("                  </li>\r\n");

            
            #line 61 "..\..\Views\Book\Index.cshtml"
               } else {
                  foreach (var version in book.Versions) {

            
            #line default
            #line hidden
WriteLiteral("                     <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2534), Tuple.Create("\"", 2631)
            
            #line 64 "..\..\Views\Book\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2541), Tuple.Create<System.Object, System.Int32>(Url.Action("Read", "Chapter", new{ id = version.DefaultReadChapter }, Request.Url.Scheme)
            
            #line default
            #line hidden
, 2541), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                           ");

            
            #line 65 "..\..\Views\Book\Index.cshtml"
                      Write(version.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                     </li>\r\n");

            
            #line 68 "..\..\Views\Book\Index.cshtml"
                  }
               }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n         </div>\r\n");

            
            #line 72 "..\..\Views\Book\Index.cshtml"
         index++;
         if (index == 3) {
            
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Book\Index.cshtml"
       Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Book\Index.cshtml"
                               
            index = 0;
         }
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 78 "..\..\Views\Book\Index.cshtml"
       if (index == 1) {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"large-4 medium-6 small-12 columns\"");

WriteLiteral(">&nbsp;</div>\r\n");

WriteLiteral("         <div");

WriteLiteral(" class=\"large-4 medium-6 small-12 columns\"");

WriteLiteral(">&nbsp;</div>\r\n");

            
            #line 81 "..\..\Views\Book\Index.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 82 "..\..\Views\Book\Index.cshtml"
       if (index == 2) {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"large-4 medium-6 small-12 columns\"");

WriteLiteral(">&nbsp;</div>\r\n");

            
            #line 84 "..\..\Views\Book\Index.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 85 "..\..\Views\Book\Index.cshtml"
       if (index != 0) {
         
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Book\Index.cshtml"
    Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Book\Index.cshtml"
                            
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 88 "..\..\Views\Book\Index.cshtml"
       if (@Model.PageCount > 1) {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"small-12 large-12 columns\"");

WriteLiteral(">\r\n               Page ");

            
            #line 91 "..\..\Views\Book\Index.cshtml"
                Write(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber);

            
            #line default
            #line hidden
WriteLiteral(" of ");

            
            #line 91 "..\..\Views\Book\Index.cshtml"
                                                                               Write(Model.PageCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("               ");

            
            #line 92 "..\..\Views\Book\Index.cshtml"
          Write(Html.PagedListPager(Model, page => Url.Action ("Index", new {page})));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n         </div>\r\n");

            
            #line 95 "..\..\Views\Book\Index.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("   </div>\r\n</div>\r\n");

            
            #line 98 "..\..\Views\Book\Index.cshtml"
 if (Request.IsAuthenticated && User.IsInRole ("Creator")) {

            
            #line default
            #line hidden
WriteLiteral("   <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"small-12 medium-4 large-4 columns\"");

WriteLiteral(">\r\n         <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3801), Tuple.Create("\"", 3863)
            
            #line 101 "..\..\Views\Book\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3808), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", "Book", null, Request.Url.Scheme)
            
            #line default
            #line hidden
, 3808), false)
);

WriteLiteral(" class=\"button success expand tiny\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"icon-plus\"");

WriteLiteral("></i> New Book\r\n         </a>\r\n      </div>\r\n   </div>\r\n");

            
            #line 106 "..\..\Views\Book\Index.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
