#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekDeepWithin.Views.Book
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Book/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<SeekDeepWithin.Models.BookViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Book\Index.cshtml"
  
   ViewBag.Title = "Read";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>\r\n   Read\r\n");

            
            #line 8 "..\..\Views\Book\Index.cshtml"
   
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Book\Index.cshtml"
    if (Request.IsAuthenticated && User.IsInRole ("Creator")) {

            
            #line default
            #line hidden
WriteLiteral("      <small>\r\n");

WriteLiteral("         ");

            
            #line 10 "..\..\Views\Book\Index.cshtml"
    Write(Html.ActionLink("new book", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </small>\r\n");

            
            #line 12 "..\..\Views\Book\Index.cshtml"
   }

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"large-3 small-12 columns\"");

WriteLiteral(">\r\n      <h3>Filters....</h3>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"large-9 columns\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Book\Index.cshtml"
      
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Book\Index.cshtml"
        
         int index = 0;
      
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Views\Book\Index.cshtml"
      
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Book\Index.cshtml"
       foreach (var book in Model) {
         if (index == 0) {
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Book\Index.cshtml"
       Write(Html.Raw("<div class=\"row\" data-equalizer>"));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Book\Index.cshtml"
                                                           
         }

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"large-6 small-12 columns\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"pricing-table\"");

WriteLiteral(" data-equalizer-watch>\r\n               <li");

WriteLiteral(" class=\"title\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Book\Index.cshtml"
                                  if (book.Versions.Count == 1 && book.Versions.First ().Name == "default") {
                      
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Book\Index.cshtml"
                 Write(book.Versions.First().Title);

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Book\Index.cshtml"
                                                  
                   } else {
                      
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Book\Index.cshtml"
                 Write(book.Title);

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Book\Index.cshtml"
                                 
                   }

            
            #line default
            #line hidden
WriteLiteral("               </li>\r\n               <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n");

WriteLiteral("                  ");

            
            #line 35 "..\..\Views\Book\Index.cshtml"
             Write(book.Summary);

            
            #line default
            #line hidden
WriteLiteral("\r\n               </li>\r\n");

            
            #line 37 "..\..\Views\Book\Index.cshtml"
               
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Book\Index.cshtml"
                if (book.Versions.Count == 0) {

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label secondary\"");

WriteLiteral(">No information has been entered for this book!</span></li>\r\n");

            
            #line 39 "..\..\Views\Book\Index.cshtml"
               } else if (book.Versions.Count == 1) {

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"cta-button\"");

WriteLiteral(">\r\n                     <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1364), Tuple.Create("\"", 1440)
            
            #line 41 "..\..\Views\Book\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1371), Tuple.Create<System.Object, System.Int32>(Url.Action("About", "Version", new {id = book.Versions.First ().Id})
            
            #line default
            #line hidden
, 1371), false)
);

WriteLiteral(" class=\"button\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"icon-book\"");

WriteLiteral("></i> Read\r\n                     </a>\r\n                  </li>\r\n");

            
            #line 45 "..\..\Views\Book\Index.cshtml"
               } else {

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral("><strong>Versions:</strong></li>\r\n");

            
            #line 47 "..\..\Views\Book\Index.cshtml"
                     foreach (var version in book.Versions) {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\Book\Index.cshtml"
                                           Write(Html.ActionLink(version.Title, "About", "Version", new{id=version.Id}, null));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 49 "..\..\Views\Book\Index.cshtml"
                  }
               }

            
            #line default
            #line hidden
WriteLiteral("               ");

            
            #line 51 "..\..\Views\Book\Index.cshtml"
                if (Request.IsAuthenticated && User.IsInRole ("Creator")) {

            
            #line default
            #line hidden
WriteLiteral("                  <li");

WriteLiteral(" class=\"bullet-item\"");

WriteLiteral(">\r\n                     <small>\r\n");

WriteLiteral("                        ");

            
            #line 54 "..\..\Views\Book\Index.cshtml"
                   Write(Html.ActionLink("Add Version", "Create", "Version", new { bookId = book.Id }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                     </small>\r\n                  </li>\r\n");

            
            #line 57 "..\..\Views\Book\Index.cshtml"
               }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n         </div>\r\n");

            
            #line 60 "..\..\Views\Book\Index.cshtml"
         index++;
         if (index == 2) {
            
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Book\Index.cshtml"
       Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Book\Index.cshtml"
                               
            index = 0;
         }
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 66 "..\..\Views\Book\Index.cshtml"
       if (index != 0) {
         
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Book\Index.cshtml"
    Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Book\Index.cshtml"
                            ;
      }

            
            #line default
            #line hidden
WriteLiteral("   </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
